config/routes.rb
Rails.application.routes.draw do
  
  root to: "shoes#index"
  resources :shoes

  resources :blogs

  devise_for :users

  post "checkout/buy", to: "checkout#buy"
  get "checkout/success", to: "checkout#success"
  get "checkout/cancel", to: "checkout#cancel"

  get "orders", to: "orders#index"
  get "orders/buyer", to: "orders#buyer"
  get "orders/seller", to: "orders#seller"
  
  post "shoes/add_to_cart/:id", to: "shoes#add_to_cart", as: "add_to_cart"
  delete "shoes/remove_from_cart/:id", to: "shoes#remove_from_cart", as: "remove_from_cart"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user

    has_one_attached :cover

    validates :title, :author, :post, presence: true

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :shoe_categories
    has_many :shoes, through: :shoe_categories
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :shoe_orders
  has_many :shoes, through: :shoe_orders

  validates :total_ammount, presence: true
  
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :user
  has_many :shoe_categories
  has_many :categories, through: :shoe_categories
  has_many :shoe_order
  has_many :orders, through: :shoe_orders

  has_one_attached :photo

  validates :name, :price, :description, :stock, :brand, :size, presence: true

  # Create array with categories names
  def categories_to_csv
    categories.map { |category| category.name }.join(", ")
  end

  # Create array with orders id
  def orders_to_csv
    orders.map { |order| order.id}.join(", ")
  end

end

app/models/shoe_category.rb
class ShoeCategory < ApplicationRecord
  belongs_to :shoe
  belongs_to :category
end

app/models/shoe_order.rb
class ShoeOrder < ApplicationRecord
  belongs_to :shoe
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :shoes
  has_many :orders
  has_many :blogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :initialize_session
  before_action :load_cart

  include Pundit
  
  private
  
  def initialize_session
    session[:cart] ||= [] 
  end
  
  def load_cart
    # Find shoe that is added to the cart during the session and load the cart
    @cart = Shoe.find(session[:cart])
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :check_auth, except: [:index, :show]
  
  def index
    # Get all the blog posts and order in decrescent order 
    @blogs = Blog.order(created_at: :desc)
  end

  def show
  end

  def new
    # Create a new blog post. Use as a model to form 
    @blog = Blog.new
  end

  def create
    # Create a new blog post. If input valid, save
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id if current_user
      if @blog.save
        redirect_to @blog
      else 
        flash.now[:errors] = @blog.errors.full_messages
        render action: "new"
      end 
  end

  def edit
  end

  def update
    # Update blog post 
    if @blog.update(blog_params)
      redirect_to @blog
    else 
      flash.now[:errors] = @blog.errors.full_messages
      render action: "edit"
    end 
  end

  def destroy
    # Delete blog post
    @blog.destroy
      redirect_to blogs_path
  end

  private

  def set_blog
    # Get blog post using the blog post params
    @blog = Blog.find(params[:id])
  end

  def blog_params 
    params.require(:blog).permit(:title, :author, :post, :cover, :user)
  end

  def check_auth
    authorize Blog
  end
  
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:buy]

    def buy
        # Populate an array with all the products presented in cart
        @products = @cart.map do |p| 
            {price_data: {
                unit_amount: (p.price.to_f * 100).to_i,
                currency: 'aud',
                product_data: {
                    name: p.name,
                  },
                },
                quantity: 1,
            }
        end

        Stripe.api_key = ENV["STRIPE_PRIVATE_KEY"]
        session = Stripe::Checkout::Session.create({
            payment_method_types: ['card'],
            line_items: @products,
            mode: 'payment',
            success_url: checkout_success_url,
            cancel_url: checkout_cancel_url,
        })

        render json: session 
    end

    def success
        # Reduce stock level
        total_ammount = 0
        @cart.each do |item|
            item.decrement!(:stock)
            total_ammount += item.price * 1
        end

        # Add and save succesful order to Order model
        Order.create(user_id: current_user.id, shoes: @cart, total_ammount: total_ammount)
        
        # Empty cart and empty session cart 
        @cart = []
        session[:cart] = []
    end

    def cancel
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    
    def index
    end

    def buyer
        # Find orders that belongs to current user
        @orders_user = Order.where(user_id: current_user.id)
        @orders = @orders_user.order(created_at: :desc)
    end

    def seller
        # Get shoes that belongs to current user 
        @shoes = Shoe.where(user_id: current_user.id)
    end

end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]
  before_action :check_auth, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit, :create, :update]
  
  def add_to_cart
    # Add shoe to cart during session using shoe params
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to shoes_path
  end

  def remove_from_cart
    # Remove shoe to cart during session using shoe params
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to shoes_path
  end

  def index 
    # Get all shoes and order according to creation time
    @shoes = Shoe.order(:created_at)
  end 

  def show
  end 

  def new
    # Create a shoe. Use as a model to form 
    @shoe = Shoe.new
  end
    
  def create
    # Create a new shoe. If input valid, save  
    @shoe = Shoe.new(shoe_params)
    @shoe.user_id = current_user.id
    if @shoe.save
      redirect_to @shoe
    else 
      flash.now[:errors] = @shoe.errors.full_messages
      render action: "new"
    end 
  end

  def edit
  end
    
  def update
    # Update shoe
    if @shoe.update(shoe_params)
      redirect_to shoe_path(@shoe)
    else
      flash.now[:errors] = @shoe.errors.full_messages
      render action: "edit"
    end
  end

  def destroy
    # Delete instances related to shoe in the join table
    @shoecategories = ShoeCategory.where(shoe_id: @shoe.id)
    @shoecategories.each do |shoecategory|
      shoecategory.destroy
    end
    # Delete shoe
    @shoe.destroy
    redirect_to shoes_path
  end
    
  private

  def set_shoe
    # Get shoe using the blog post params
    @shoe = Shoe.find(params[:id])
  end

  def set_categories
    # Get all categories and order according to category's name 
    @categories = Category.order(:name)
  end
    
  def shoe_params
    params.require(:shoe).permit(:name, :description, :price, :brand, :size, :stock, :photo, category_ids: [])
  end

  def check_auth
    authorize @shoe
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/blogs/_form.html.erb
<%= form_with model: @blog, local: true do |f| %>
    <p>
        <%=f.label :title %>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :author %>
        <%= f.text_field :author %>
    </p>
    <p>
        <%= f.label :post %>
        <%= f.text_field :post%>
    </p>
    <p>
        <%= f.label :cover %>
        <%= f.file_field :cover %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render "form" %>

app/views/blogs/index.html.erb
<% if policy(Blog).new? %>
    <br>
    <h3 class="text-center"><%= link_to 'Create a new blog post', new_blog_path %></h3>
    <br>
    <hr>
<% end %>
<div class="mx-3">
<% @blogs.each do |post| %>
    <h2><%= link_to post.title, blog_path(post) %></h2>
    <h3>By <%= post.author %></h3>
    <div class="d-flex flex-wrap">
        <% if post.cover.attached? %>
            <p><%= cl_image_tag post.cover.key, crop: :scale, width: 300, cloud_name: "rafaelmellocloud" %></p>
        <% end %>
        <p><%= post.post %></p>
    </div>
    <hr>          
<% end %>
</div>

app/views/blogs/new.html.erb
<h1>New Blog Post</h1>

<%= render "form" %>

app/views/blogs/show.html.erb
<div class="mx-3">   
    <h2><%= @blog.title %></h2>
    <h3>By <%= @blog.author%></h3>
    <% if @blog.cover.attached? %>
        <%= cl_image_tag @blog.cover.key, crop: :scale, width: 500, cloud_name: "rafaelmellocloud", class:"d-flex" %>
    <% end %>
    <p><%= @blog.post %></p>
    <%= link_to "<< Back", :back %> 
    <%= link_to "Edit", edit_blog_path(@blog) if policy(Blog).edit? %>
    <%= link_to "Delete", @blog, method: :delete, data: { confirm: "Are you sure?" } if policy(Blog).destroy?%>
</div>

app/views/checkout/cancel.html.erb
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>

app/views/checkout/success.html.erb
<body>
  <section>
    <p>
      We appreciate your business! If you have any questions, please email
      <a href="mailto:orders@niceshoesapp.com">orders@niceshoesapp.com</a>.
    </p>
  </section>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Niceshoes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>

  </head>

  <body>
    <header>
      <nav class="navbar navbar-light text-white bg-secondary">
        <div class="container-fluid">
          <a class="navbar-brand fs-2 text-white">Nice Shoes</a>
          <span class="d-flex">
            <% if user_signed_in? %>
              <%= current_user.email %>
              |
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to "Login", new_user_session_path %>
              |
              <%= link_to "Sign up", new_user_registration_path %>
            <% end %>
          </span>
        </div>
      </nav>
    </header>
    <ul class="nav nav-pills nav-justified">
      <li class="nav-item">
        <%= link_to "Buying", root_path, class:"nav-link fs-3" %>
      </li>
      <li class="nav-item">
        <%= link_to "Selling", new_shoe_path, class:"nav-link fs-3"  %>
      </li>
      <li class="nav-item">
        <%= link_to "Orders", orders_path, class:"nav-link fs-3"  %>
      </li>
      <li class="nav-item">
        <%= link_to "Blog", blogs_path, class:"nav-link fs-3"  %>
      </li>
    </ul>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <% if flash[:errors] %>
      <section class="errors">
        <p class="title">The following errors occured:</p>
        <ul>
          <% flash[:errors].each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </section>
    <% end %>
    <% if @cart.present? %>
      <hr>
      <h3>Shopping cart</h3>
      Items:
      <%= @cart.size %>
      <br>
      <% @cart.each do |cart_item| %>
        <br>
        <%= cart_item.name %>
        <%= "- A$#{cart_item.price}" %>
        <%= link_to "Remove from cart", remove_from_cart_path(cart_item), method: :delete %>
      <% end %>
      <br><br>
      <% if @cart.present? %>
        <button id="checkout-button">Buy now!</button>
      <% end %>
    <% end %>
    <hr>
    <%= yield %>
  </body>
</html>


<script type="text/javascript">
  var stripe = Stripe("<%= ENV["STRIPE_PUBLISHABLE_KEY"] %>");
  var checkoutButton = document.getElementById("checkout-button");
  checkoutButton.addEventListener("click", function () {
    fetch("/checkout/buy", {
      method: "POST",
    })
      .then(function (response) {
        return response.json();
      })
      .then(function (session) {
        return stripe.redirectToCheckout({ sessionId: session.id });
      })
      .then(function (result) {
        // If redirectToCheckout fails due to a browser or network
        // error, you should display the localized error message to your
        // customer using error.message.
        if (result.error) {
          alert(result.error.message);
        }
      })
      .catch(function (error) {
        console.error("Error:", error);
      });
  });
</script>

app/views/orders/buyer.html.erb
<% @orders.each do |order|%>
    <% order.shoe_orders.each do |shoe_order| %>
        <p>Order number: <%= shoe_order.order.id %></p>
        <p>Date: <%= shoe_order.order.created_at %></p>
        <p>Item name: <%= shoe_order.shoe.name %></p>
        <p>Item brand name: <%= shoe_order.shoe.brand %></p>
        <p>Please contact seller to organize delivery: <%= shoe_order.shoe.user.email %></p>
    <hr>
    <% end %>
<% end %>

app/views/orders/index.html.erb
<div class="d-flex flex-column align-items-center justify-content-center">
    <h2><%= link_to "Track Orders", orders_buyer_path %></h2>
    <h2><%= link_to "Track Sellings", orders_seller_path %></h2>
</div>

app/views/orders/seller.html.erb
<% @shoes.each do |shoe| %>
    <% shoe.shoe_order.each do |shoe_order| %>
        <p>SOLD</p>
        <p>Order number: <%= shoe_order.order.id %></p>
        <p>Date: <%= shoe_order.order.created_at %></p>
        <p>Item name: <%= shoe_order.shoe.name %></p>
        <p>Item brand name: <%= shoe_order.shoe.brand %></p>
        <p>Please contact buyer to organize delivery: <%= shoe_order.order.user.email %></p>
        <hr>
    <%end %>
<% end %>

app/views/shoes/_form.html.erb
<div class="mx-3">  
    <%= form_with model: @shoe, local: true do |f| %>
        <p class="form-control">
            <%=f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
        </p>
        <p class="form-control">
            <%=f.label :brand %>
            <%= f.text_field :brand, class: "form-control" %>
        </p>
        <p class="form-control">
            <%= f.label :description, for: "exampleFormControlTextarea1" %>
            <%= f.text_area :description, class: "form-control", id:"exampleFormControlTextarea1", rows:"3" %>
        </p>
        <p class="form-control">
            <%= f.label :price %>
            <%= f.number_field :price, class: "form-control" %>
        </p>
        <p class="form-control"> 
            <%= f.label :size %>
            <%= f.number_field :size, class: "form-control" %>
        </p>
        <p class="form-control">
            <%= f.label :stock %>
            <%= f.number_field :stock, class: "form-control" %>
        </p>
        <p class="form-control">
            <%= f.label :categories %>
            <%= f.collection_check_boxes :category_ids, @categories, :id, :name, class: "form-control" %>
        </p>
        <p class="form-control">
            <%= f.label :photo %>
            <%= f.file_field :photo, class: "form-control" %>
        </p>
        <p class="btn btn-primary">
            <%= f.submit %>
        </p>
    <% end %>
</div> 

app/views/shoes/edit.html.erb
<h3>Update a shoe</h3>

<%= render "form" %>

app/views/shoes/index.html.erb
<div class="d-flex align-content-stretch flex-wrap justify-content-around">
  <% @shoes.each do |shoe| %>
  <div class="card" style="width: 23rem;">
    <% if shoe.photo.attached? %>
      <img class="card-img-top" alt="Shoes"<%= cl_image_tag shoe.photo.key, crop: :scale, width: 500, cloud_name: "rafaelmellocloud" %> 
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= link_to shoe.name, shoe_path(shoe) %></h1></h5>
      <p class="card-text"><%= shoe.brand %></p>
      <p class="price"><%= "A$#{shoe.price}" %></p>
      <% if @cart.include?(shoe) %>
        <a href="#" class="btn btn-primary"><%= button_to "Remove from cart", remove_from_cart_path(shoe), method: :delete %></a>
      <% elsif shoe.stock == 0 %>
        <button class="btn btn-primary">Sold Out!</button>
      <% else %>
        <%= button_to "Add to cart", add_to_cart_path(shoe) %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/shoes/new.html.erb
<h3 class="text-center text-primary">Selling</h3>

<%= render "form" %>

app/views/shoes/show.html.erb
<div class="d-flex flex-wrap">
<div class="d-flex align-items-center">
  <% if @shoe.photo.attached? %>
      <p><%= cl_image_tag @shoe.photo.key, crop: :scale, width: 500, cloud_name: "rafaelmellocloud" %></p>
  <% end %>
</div>
<div class="d-flex flex-column align-items-center justify-content-center mx-5">
  <h2><%= @shoe.name %></h2>
  <h2><%= @shoe.brand %></h2>

  <p><%= @shoe.description %></p>

  <h4>AUD$ <%= @shoe.price.to_i %></h4>

  <h4>Size: AU <%= @shoe.size %></h4>

  <p><%= @shoe.categories_to_csv %></p>

  <% if @cart.include?(@shoe) %>
    <%= button_to "Remove from cart", remove_from_cart_path(@shoe), method: :delete %>
  <% elsif @shoe.stock == 0 %>
    <button>Sold Out!</button>
  <% else %>
    <%= button_to "Add to cart", add_to_cart_path(@shoe) %>
  <% end %>
  <br>
  <p><%= link_to "Edit", edit_shoe_path(params[:id]) if policy(@shoe).edit? %></p>
  <p><%= link_to "Delete", @shoe, method: :delete, data: { confirm: "Are you sure?" } if policy(@shoe).edit? %>
  <p><%= link_to "<< Back to menu", root_path %></p>
</div>
</div>